server:
  servlet.context-path: /tm/v1
  port: ${SERVER_PORT:8080}


spring:
  datasource:
    driverClassName: org.postgersql.Driver
    url: jdbc:postgresql://db:5432/tm
    username: tm
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: validate
    # show-sql: true
    # properties.hibernate.format_sql: true
  database-platform: org.hibernate.dialect.PostgreSQL16Dialect

  liquibase:
    change-log: classpath:db/changelog/changelog-main.xml

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties.mail.smtp:
      auth: true
      starttls.enable: true


app:
  kafka:
    enabled: true
    bootstrapAddress: ${KAFKA_BOOTSTRAP_ADDRESS:http://localhost:9091}
    groupId: task-manager
  recipient.mail: ${RECIPIENT_MAIL}

logging:
  level:
    org.hibernate:
      SQL: TRACE
      type: INFO
      orm.jdbc.bind: INFO